### ISSUE TITLE
icons broken

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio-book#6]
![image](https://github.com/PathVisio/pathvisio-book/assets/26721/05eaf8d7-6de7-4cbc-89f9-947f5093dedd)

(I may find time to look at the cause)

**Comment by Finterly** [comment]
Commit 3dd1a3c fixes issue #6

Was an issue of file path being ".PNG" when they should be ".png"

**Comment by egonw** [comment]
oh, that was quick. Thanks!!
